package dev.linhtetko.j2kauto.codegen

import com.squareup.kotlinpoet.BOOLEAN
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.DOUBLE
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.INT
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.LIST
import com.squareup.kotlinpoet.LONG
import com.squareup.kotlinpoet.ParameterSpec
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.STRING
import com.squareup.kotlinpoet.TypeName
import com.squareup.kotlinpoet.TypeSpec
import dev.linhtetko.j2kauto.engine.FileSchemas
import dev.linhtetko.j2kauto.engine.InferredType
import dev.linhtetko.j2kauto.engine.NamedClass
import dev.linhtetko.j2kauto.engine.Names
import dev.linhtetko.j2kauto.engine.ScalarKind
import dev.linhtetko.j2kauto.engine.SchemaRegistry

/** Emits one KotlinPoet [FileSpec] per JSON input file. */
object KotlinFileGenerator {

    fun generate(
        file: FileSchemas,
        strategy: AnnotationStrategy,
        options: CodegenOptions,
        classByShape: Map<InferredType.ObjectType, NamedClass>,
    ): FileSpec {
        // Name the .kt file after the first class actually emitted here so two
        // inputs with the same file name can't overwrite each other's output.
        val fileName = file.classes.firstOrNull()?.name ?: file.rootClassName
        val builder = FileSpec.builder(file.packageName, fileName)
            .addFileComment("Generated by j2k-auto from %L — do not edit.", file.fileName)
        for (cls in file.classes) {
            builder.addType(buildClass(cls, classByShape, strategy, options))
        }
        return builder.build()
    }

    private fun buildClass(
        cls: NamedClass,
        classByShape: Map<InferredType.ObjectType, NamedClass>,
        strategy: AnnotationStrategy,
        options: CodegenOptions,
    ): TypeSpec {
        val classBuilder = TypeSpec.classBuilder(cls.name).addModifiers(KModifier.DATA)
        when (options.visibility) {
            dev.linhtetko.j2kauto.Visibility.PUBLIC -> classBuilder.addModifiers(KModifier.PUBLIC)
            dev.linhtetko.j2kauto.Visibility.INTERNAL -> classBuilder.addModifiers(KModifier.INTERNAL)
            dev.linhtetko.j2kauto.Visibility.PRIVATE -> classBuilder.addModifiers(KModifier.PRIVATE)
        }
        strategy.classAnnotations().forEach(classBuilder::addAnnotation)

        val constructor = FunSpec.constructorBuilder()
        val usedPropertyNames = mutableSetOf<String>()
        cls.type.fields.entries.forEachIndexed { index, (key, field) ->
            val propertyName = uniquePropertyName(key, index, usedPropertyNames)
            val typeName = typeNameOf(field.type, classByShape, strategy)

            val parameter = ParameterSpec.builder(propertyName, typeName)
            strategy.propertyAnnotations(key, propertyName, options.alwaysAnnotate)
                .forEach(parameter::addAnnotation)
            if (typeName.isNullable && options.defaultsForNullable) {
                parameter.defaultValue("null")
            }
            constructor.addParameter(parameter.build())

            classBuilder.addProperty(
                PropertySpec.builder(propertyName, typeName)
                    .initializer(propertyName)
                    .mutable(options.useVar)
                    .build(),
            )
        }
        return classBuilder.primaryConstructor(constructor.build()).build()
    }

    private fun uniquePropertyName(key: String, index: Int, used: MutableSet<String>): String {
        var name = Names.propertyName(key).ifEmpty { "field${index + 1}" }
        var i = 2
        while (name in used) {
            name = Names.propertyName(key) + i
            i++
        }
        used += name
        return name
    }

    private fun typeNameOf(
        type: InferredType,
        classByShape: Map<InferredType.ObjectType, NamedClass>,
        strategy: AnnotationStrategy,
    ): TypeName {
        val base: TypeName = when (type) {
            is InferredType.Scalar -> when (type.kind) {
                ScalarKind.BOOLEAN -> BOOLEAN
                ScalarKind.INT -> INT
                ScalarKind.LONG -> LONG
                ScalarKind.DOUBLE -> DOUBLE
                ScalarKind.STRING -> STRING
            }
            is InferredType.ArrayType ->
                LIST.parameterizedBy(typeNameOf(type.element, classByShape, strategy))
            is InferredType.ObjectType ->
                if (type.fields.isEmpty()) {
                    // An always-empty object carries no information — don't emit a fieldless class.
                    strategy.anyType()
                } else {
                    val named = classByShape.getValue(SchemaRegistry.structuralKey(type))
                    ClassName(named.packageName, named.name)
                }
            is InferredType.JsonAny -> strategy.anyType()
            is InferredType.NullType -> strategy.anyType()
        }
        return base.copy(nullable = type.nullable)
    }
}
