package dev.linhtetko.j2kauto.codegen

import dev.linhtetko.j2kauto.AnnotationStyle
import org.junit.jupiter.api.Test
import kotlin.test.assertEquals

/** Golden test: the full KOTLINX pipeline output for a representative payload. */
class KotlinxGenerationTest {

    @Test
    fun `kotlinx output matches golden text`() {
        val input = JsonInput(
            "user_profile.json",
            """
            {
              "id": 1,
              "user_name": "lin",
              "score": 9.5,
              "is_active": true,
              "home_address": {"street_name": "Orchard", "unit_no": null},
              "work_address": {"street_name": "Raffles", "unit_no": "12-03"},
              "orders": [
                {"order_id": 1, "note": "first"},
                {"order_id": 2}
              ],
              "tags": [],
              "object": "keyword-key"
            }
            """.trimIndent(),
        )

        val generated = J2kPipeline.generate(listOf(input), "com.example.model", AnnotationStyle.KOTLINX)
            .single()
            .toString()

        val expected = """
            |// Generated by j2k-auto from user_profile.json — do not edit.
            |package com.example.model
            |
            |import kotlin.Boolean
            |import kotlin.Double
            |import kotlin.Int
            |import kotlin.String
            |import kotlin.collections.List
            |import kotlinx.serialization.SerialName
            |import kotlinx.serialization.Serializable
            |import kotlinx.serialization.json.JsonElement
            |
            |@Serializable
            |public data class UserProfile(
            |  public val id: Int,
            |  @SerialName("user_name")
            |  public val userName: String,
            |  public val score: Double,
            |  @SerialName("is_active")
            |  public val isActive: Boolean,
            |  @SerialName("home_address")
            |  public val homeAddress: HomeAddress,
            |  @SerialName("work_address")
            |  public val workAddress: HomeAddress,
            |  public val orders: List<Order>,
            |  public val tags: List<JsonElement?>,
            |  public val `object`: String,
            |)
            |
            |@Serializable
            |public data class HomeAddress(
            |  @SerialName("street_name")
            |  public val streetName: String,
            |  @SerialName("unit_no")
            |  public val unitNo: String? = null,
            |)
            |
            |@Serializable
            |public data class Order(
            |  @SerialName("order_id")
            |  public val orderId: Int,
            |  public val note: String? = null,
            |)
            |
        """.trimMargin()

        assertEquals(expected, generated)
    }
}
