package dev.linhtetko.j2kauto.codegen

import dev.linhtetko.j2kauto.AnnotationStyle
import org.junit.jupiter.api.Test
import kotlin.test.assertEquals

/** Golden tests: one small fixture across the MOSHI / GSON / NONE strategies. */
class StyleMatrixTest {

    private val input = JsonInput("pet.json", """{"pet_name": "Milo", "age": 3}""")

    private fun generate(style: AnnotationStyle): String =
        J2kPipeline.generate(listOf(input), "com.example", style).single().toString()

    @Test
    fun moshi() {
        val expected = """
            |// Generated by j2k-auto from pet.json — do not edit.
            |package com.example
            |
            |import com.squareup.moshi.Json
            |import com.squareup.moshi.JsonClass
            |import kotlin.Int
            |import kotlin.String
            |
            |@JsonClass(generateAdapter = true)
            |public data class Pet(
            |  @Json(name = "pet_name")
            |  public val petName: String,
            |  public val age: Int,
            |)
            |
        """.trimMargin()
        assertEquals(expected, generate(AnnotationStyle.MOSHI))
    }

    @Test
    fun gson() {
        val expected = """
            |// Generated by j2k-auto from pet.json — do not edit.
            |package com.example
            |
            |import com.google.gson.annotations.SerializedName
            |import kotlin.Int
            |import kotlin.String
            |
            |public data class Pet(
            |  @SerializedName("pet_name")
            |  public val petName: String,
            |  public val age: Int,
            |)
            |
        """.trimMargin()
        assertEquals(expected, generate(AnnotationStyle.GSON))
    }

    @Test
    fun none() {
        val expected = """
            |// Generated by j2k-auto from pet.json — do not edit.
            |package com.example
            |
            |import kotlin.Int
            |import kotlin.String
            |
            |public data class Pet(
            |  public val petName: String,
            |  public val age: Int,
            |)
            |
        """.trimMargin()
        assertEquals(expected, generate(AnnotationStyle.NONE))
    }
}
